Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\libxl.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\GGDBDataAwareCtrl.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\GGDBDataAwareCtrl.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\CmdCore.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\CmdCore.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\Common.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\Common.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\GMath.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\GMath.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\Geometry.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\Geometry.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\ArchiAlgo.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\ArchiAlgo.lib ..\..\lib\win32  
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\GGDB.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\GGDB.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDB.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\MDB.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDB.pdb ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDCache.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\MDCache.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDCache.pdb ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDCmdLog.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\MDCmdLog.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDCmdLog.pdb ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDCommon.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\MDCommon.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDCommon.pdb ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDScript.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\MDScript.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MDScript.pdb ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\RenderSystemGL.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\MaterialCore.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\DBOperations.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\DBOperations.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\DBOperations.pdb ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\GP.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\GP.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\ViewCore.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\ViewCore.lib ..\..\lib\win32  
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\ViewManager.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\ViewManager.lib ..\..\lib\win32  
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\GGDBExplorer2014.exe ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\FileManagerCache.exe ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\glew32.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\glewctx.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\FreeImage.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\sqlite3.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\GGPViewerProxy.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Lib\Win32\Release\GGPViewerProxy.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\lib3ds-2_0.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\libfbxsdk.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Bin\Win32\Release\sdt.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GBIM\Win32\DBCAysTable.wat ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_system-vc100-mt-1_52.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_system-vc100-mt-gd-1_52.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_thread-vc100-mt-1_52.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_thread-vc100-mt-gd-1_52.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_chrono-vc100-mt-gd-1_52.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_date_time-vc100-mt-1_52.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_date_time-vc100-mt-gd-1_52.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_regex-vc100-mt-1_52.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_regex-vc100-mt-gd-1_52.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_chrono-vc100-mt-1_52.lib ..\..\lib\win32
echo "----------公共资源拷贝-----------------"
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\Qtitan\lib\qtnribbon3.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\Qtitan\lib\qtnribbon3.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\zlib\lib\Release\X86\zlib.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\GLDTechPlatform\bin\Release\X86\GLDTechPlatform.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\GLDTechPlatform\bin\Release\X86\GMPRibbonStyle.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GlodonResource\GLDTechPlatform\bin\Release\X86\GMPRibbonStyle.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDCommon.dll ..\..\bin 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDCommon.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDCrypt.dll ..\..\bin 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDCrypt.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDTableView.dll ..\..\bin 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDTableView.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDWidget.dll ..\..\bin 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDWidget.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDXML.dll ..\..\bin 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDXML.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDZip.dll ..\..\bin 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDZip.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GSP.dll ..\..\bin 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GSP.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDStyles.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDStyles.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDThemeEngine.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GLDThemeEngine.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GMPUIExtends.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GMPUIExtends.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GEPEngine.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GUC.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GUC.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GSC.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GSCAppImpl.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GSCCore.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\slm_runtime_api.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\virbox.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\virbox_interlock.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\virbox_str.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\virboxRT.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GRPCommon.dll ..\..\bin 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GRPCommon.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GRPEngine.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\GDownload.dll ..\..\bin\update\version
Copy /Y ..\..\..\..\Externals\GlodonResource\Glodon\bin\Release\X86\MagicTrace.dll ..\..\bin\update\version
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\RichText\lib\Release\X86\RichText.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\lzma\C\lzma\lib\Release\X86\lzma.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\lzma\C\lzma\lib\Release\X86\LZMA.dll ..\..\Bin\ 
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\QuaZip\lib\Release\X86\QuaZip.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\gtest\msvc\gtest\Release\gtest.lib ..\..\lib\win32 
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\VMProtect\lib\Win32\VMProtectSDK32.lib ..\..\lib\win32
Copy /Y ..\..\..\..\Externals\GlodonResource\ThirdPart\VMProtect\bin\Win32\VMProtectSDK32.dll ..\..\Bin\
Copy /Y ..\..\..\..\Externals\GRaster\Win32\Release\NXCGRaster.dll ..\..\Bin\

echo "----------GMP控件资源拷贝-----------------"
XCopy /Y ..\..\..\..\Externals\GlodonResource\Glodon\src\GMPUIStyle\res ..\..\Bin\res  /s /e /i
XCopy /Y ..\..\..\..\Externals\GlodonResource\GLDTechPlatform\res ..\..\Bin\res  /s /e /i

Copy /Y ..\..\bin\images\logoDefault.png ..\..\Bin\res\
Copy /Y ..\..\bin\images\logoHover.png ..\..\Bin\res\
Copy /Y ..\..\bin\images\logoPressed.png ..\..\Bin\res\

echo "------------Teigha: Dll拷贝-----------------"
set TargetPath=..\..\bin\
set SourcePath="..\..\..\..\Externals\Teigha\exe\vc10dll\"

Copy /Y %SourcePath%sisl.dll %TargetPath%
Copy /Y %SourcePath%TD_Alloc_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Db_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_DbRoot_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Ge_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Gi_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Gs_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Root_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_SpatialIndex_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_BrepRenderer_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_BR_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%ExFieldEvaluator_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%ModelerGeometry_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%RasterProcessor_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%RecomputeDimBlock_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%TD_DynBlocks_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%TG_ModelerGeometry_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%WinBitmap_4.00_10.txv %TargetPath%
Copy /Y %SourcePath%TD_AcisBuilder_4.00_10.dll %TargetPath%

Copy /Y ..\..\..\..\Externals\Cloud\npSSO\win32\npSSO.dll ..\..\Bin\ 
