Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\libxl.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GGDBDataAwareCtrld.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\GGDBDataAwareCtrld.lib ..\..\..\lib\win32  
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GGDBDataAwareCtrld.pdb ..\..\..\Bin\  
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\CmdCored.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\CmdCored.lib ..\..\..\lib\win32  
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\CmdCored.pdb ..\..\..\Bin\  
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\Commond.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\Commond.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\Commond.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GMathd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\GMathd.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GMathd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\Geometryd.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\Geometryd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\Geometryd.pdb ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\ArchiAlgod.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\ArchiAlgod.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\ArchiAlgod.pdb ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GGDBd.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\GGDBd.lib ..\..\..\lib\win32  
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GGDBd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDBd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\MDBd.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDBd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDCached.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\MDCached.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDCached.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDCmdLogd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\MDCmdLogd.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDCmdLogd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDCommond.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\MDCommond.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDCommond.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDScriptd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\MDScriptd.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MDScriptd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\RenderSystemGLd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\MaterialCored.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\DBOperationsd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\DBOperationsd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\DBOperationsd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GPd.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\GPd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\ViewCored.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\ViewCored.lib ..\..\..\lib\win32  
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\ViewCored.pdb ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\ViewManagerd.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\ViewManagerd.lib ..\..\..\lib\win32  
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\ViewManagerd.pdb ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GGDBExplorer2014d.exe ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\FileManagerCached.exe ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\glew32.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\glewctx.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\FreeImaged.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\sqlite3d.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\GGPViewerProxyd.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\GGPViewerProxyd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\lib3ds-2_0d.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\libfbxsdk.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Bin\Win32\Debug\sdtD.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Lib\Win32\Debug\bsond.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Win32\DBCAysTable.wat ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\VLD\bin\Win32\dbghelp.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\VLD\bin\Win32\vld_x86.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\VLD\bin\Win32\Microsoft.DTfW.DHL.manifest ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\VLD\lib\Win32\vld.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_system-vc100-mt-1_52.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_system-vc100-mt-gd-1_52.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_thread-vc100-mt-1_52.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_thread-vc100-mt-gd-1_52.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_chrono-vc100-mt-gd-1_52.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_date_time-vc100-mt-1_52.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_date_time-vc100-mt-gd-1_52.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_regex-vc100-mt-1_52.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_regex-vc100-mt-gd-1_52.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GBIM\Externals\Thirdparty\boost-1_52\Lib\Win32\libboost_chrono-vc100-mt-1_52.lib ..\..\..\lib\win32
echo "----------公共资源拷贝-----------------"
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\Qtitan\lib\qtnribbond3.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\Qtitan\lib\qtnribbond3.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\zlib\lib\Debug\X86\zlibd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\GLDTechPlatform\bin\Debug\X86\GLDTechPlatformd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\GLDTechPlatform\bin\Debug\X86\GMPRibbonStyled.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\GLDTechPlatform\bin\Debug\X86\GMPRibbonStyled.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDCommond.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDCommond.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDCommond.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDCryptd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDCryptd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDCryptd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDTableViewd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDTableViewd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDTableViewd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDWidgetd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDWidgetd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDWidgetd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDXMLd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDXMLd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDXMLd.pdb ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDZipd.dll ..\..\..\Bin\     
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDZipd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDZipd.pdb ..\..\..\Bin\     
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GSPd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GSPd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GSPd.pdb ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDStylesd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDStylesd.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDThemeEngined.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GLDThemeEngined.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GMPUIExtendsd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GMPUIExtendsd.dll ..\..\..\Bin\ 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GEPEngined.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GUCd.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GUCd.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GSCd.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GSCAppImpld.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GSCCored.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GRPCommond.dll ..\..\Bin 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GRPCommond.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GRPEngined.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\GDownload.dll ..\..\..\Bin\update\version
Copy /Y ..\..\..\Externals\GlodonResource\Glodon\bin\Debug\X86\MagicTrace.dll ..\..\..\Bin\update\version
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\RichText\lib\Debug\X86\RichTextd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\lzma\C\lzma\lib\Debug\X86\lzmad.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\lzma\C\lzma\lib\Debug\X86\LZMA.dll ..\..\..\Bin\  
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\QuaZip\lib\Debug\X86\QuaZipd.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\gtest\msvc\gtest\Debug\gtestd.lib ..\..\..\lib\win32 
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\VMProtect\lib\Win32\VMProtectSDK32.lib ..\..\..\lib\win32
Copy /Y ..\..\..\Externals\GlodonResource\ThirdPart\VMProtect\bin\Win32\VMProtectSDK32.dll ..\..\..\Bin\
Copy /Y ..\..\..\Externals\GRaster\win32\debug\NXCGRaster.dll ..\..\..\Bin\


echo "------------Teigha: Dll拷贝-----------------"
set TargetPath=..\..\..\Bin\
echo 目标路径: %TargetPath%
set SourcePath="..\..\..\Externals\Teigha\exe\vc10dlldbg\"
echo Teigha路径: %SourcePath%

Copy /Y %SourcePath%sisl.dll %TargetPath%
Copy /Y %SourcePath%TD_Alloc_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Db_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_DbRoot_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Ge_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Gi_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Gs_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_Root_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_SpatialIndex_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_BrepRenderer_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_BR_4.00_10.dll %TargetPath%
Copy /Y %SourcePath%TD_AcisBuilder_4.00_10.dll %TargetPath%

Copy /Y %SourcePath%ExFieldEvaluator_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%ModelerGeometry_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%RasterProcessor_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%RecomputeDimBlock_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%TD_DynBlocks_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%TG_ModelerGeometry_4.00_10.tx %TargetPath%
Copy /Y %SourcePath%WinBitmap_4.00_10.txv %TargetPath%

Copy /Y %SourcePath%sisl.pdb %TargetPath%
Copy /Y %SourcePath%TD_Alloc_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_Db_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_DbRoot_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_Ge_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_Gi_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_Gs_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_Root_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_SpatialIndex_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_BrepRenderer_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_BR_4.00_10.pdb %TargetPath%
Copy /Y %SourcePath%TD_AcisBuilder_4.00_10.pdb %TargetPath%
 
Copy /Y ..\..\..\Externals\Cloud\npSSO\win32\npSSO.dll ..\..\..\Bin\ 

